config/routes.rb
WheresMyBoba::Application.routes.draw do

  root 'site#index'
  devise_for :users
  resources :site, :users

  get '/users/:id/adventures', to: 'users#adventures', as: :user_adventures
  post '/users/:id/faves', to: 'faves#create', as: :new_fave
  delete '/users/:id/faves', to: 'faves#destroy'

  
  get '/my_boba/search', to: 'my_boba#search', as: :search
  post '/my_boba/results', to: 'my_boba#results', as: :results
  get '/my_boba/adventures', to: 'adventures#all', as: :all_adventures

  get '/my_boba/:yelp_id', to: 'my_boba#show', as: :my_boba

  get 'my_boba/:yelp_id/adventures', to: 'adventures#index', as: :loc_adventures
  get 'my_boba/:yelp_id/adventures/new', to: 'adventures#new', as: :new_adventure
  get 'my_boba/:yelp_id/adventures/:id', to: 'adventures#show', as: :show_adventure
  get 'my_boba/:yelp_id/adventures/:id/edit', to: 'adventures#edit', as: :edit_adventure
  
  post 'my_boba/:yelp_id/adventures', to: 'adventures#create'
  patch 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  put 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  delete 'my_boba/:yelp_id/adventures/:id', to: 'adventures#destroy'

end

app/models/adventure.rb
# == Schema Information
#
# Table name: adventures
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  description     :text
#  cross_st1       :string(255)
#  address         :string(255)
#  city            :string(255)
#  state           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  cross_st2       :string(255)
#  user_id         :integer
#  bobalocation_id :integer
#  latitude        :float
#  longitude       :float
#

class Adventure < ActiveRecord::Base
	# belongs_to :user
    has_many :bobalocations, through: :user
	has_many :neighborhoods


end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
include AdventuresHelper
 before_filter :authenticate_user!
 before_filter :user_signed_in?, only: [:create, :new, :edit, :update]
  #before_filter :signed_in_user, only: [:create, :new, :edit, :update]
 before_filter :check_adventure_owner, only: [:destroy, :update, :edit]
  
  def index
  end

  def new
    id = params[:yelp_id]
    @user = current_user
    location = Bobalocation.find_by_yelp_id(id)


    yelp = load_yelp

    @result = yelp.search_by_business_id(id)
    @rating = @result['rating_img_url']
    yelp_id = @result['id']
    hood = @result['location']['neighborhoods']

  	@adventure = Adventure.new
  end

  def create
    id = params[:yelp_id]
    location = Bobalocation.find_by_yelp_id(id)

  	new_adventure = params.require(:adventure).permit(:name, :description, :city, :state, :address, :cross_st1, :cross_st2)
    new_adventure
    new_adventure[:user_id]= current_user.id
    new_adventure[:bobalocation_id] = location.id
    adventure = Adventure.create(new_adventure)

    redirect_to show_adventure_path(id, adventure.id)
  end

  def show
  	@adventure = Adventure.find(params[:id])
  end

  def edit
  	@adventure = Adventure.find(params[:id])
  end

  def update
    @adventure = current_user.adventures.find_by_id(params[:id])
    upd_adv = params.require(:adventure).permit(:name, :description, :city, :state, :address, :cross_st1, :cross_st2, :user_id, :bobalocation_id)

    if @adventure.update_attributes(upd_adv)
      flash[:success] = "Adventure updated!"

      id = Bobalocation.find(@adventure.bobalocation_id)
      redirect_to show_adventure_path(id.id, @adventure.id)
    else
      render :edit
    end
  end

  def all
    all = Adventure.all
    @all = all.sort { |x,y| y <=> x}
    
  end

  def destroy
    adventure = current_user.adventures.find_by_id(params[:id])
  	id = current_user.id
    adventure.delete
  	redirect_to user_adventures_path(id)

  end

private

  def load_yelp  
    consumer_key = 'pXI7O2w2TzCcH7ub3Di5Bw'
    consumer_secret = '-PlNCMY1YN1c0-Lh9H4xNWBSMh0'
    token = '7S78wEVuSybUcAc1legyfpGdPYyhsuAz'
    token_secret = 'A_vgIl-yVGp87fuPZvuyWeSXcEQ'
    keys = {consumer_key: consumer_key, consumer_secret: consumer_secret, token: token, token_secret: token_secret}
    yelp = YelpApi.new(keys)
  end 
  
end

app/helpers/adventures_helper.rb
module AdventuresHelper

def check_adventure_owner
		adventure = current_user.adventures.where(:id => params[:id]).first
    	if adventure.nil?
    		flash[:error] = "That's not your adventure."
			redirect_to adventure_path(params[:id])
		end
	end


end

app/views/adventures/_form.html.erb
<%= form_for(:adventure, as: :post, url: loc_adventures_path) do |f| %>
  <%= f.text_field :name, :autofocus => true, placeholder: "the adventure!" %>
  <br>
  <%= f.text_field :description, placeholder: "describe it" %>
  <br>
  <%= f.text_field :city, placeholder: "city" %>
  <br>
  <%= f.text_field :state, placeholder: "state" %>
  <br>
  <%= f.text_field :cross_st1, placeholder: "cross street 1" %>
  <br>
  <%= f.text_field :cross_st2, placeholder: "cross street 2" %>
  <br>
  <%= f.text_field :address, placeholder: "address" %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/adventures/all.html.erb
ALL ADVENTURES

<% if signed_in? %>
  <table>
  	<% @all.each do |a| %>
    <tr>
    	<td>
    		<%= a.name %>
    	</td>
    </tr>
    <% end %>
  </table> 
<% else %>
<div class='text-center'>
	<h3> THERE ARE </H3>	  
	<H1><%= @all.length %></H1>
	<H3> ADVENTURES!</h3>
    <br />
	  <div>

  </div>
</div>
<% end %>

app/views/adventures/edit.html.erb
<div class='col-xs-12 text-center'>

<h2>Edit Adventure!</h2>

<%= form_for(:adventure, method: :patch, url: show_adventure_path) do |f| %>
  <%= f.text_field :name, :autofocus => true, placeholder: "the adventure!" %>
  <br>
  <%= f.text_field :description, placeholder: "describe it" %>
  <br>
  <%= f.text_field :city, placeholder: "city" %>
  <br>
  <%= f.text_field :state, placeholder: "state" %>
  <br>
  <%= f.text_field :cross_st1, placeholder: "cross street 1" %>
  <br>
  <%= f.text_field :cross_st2, placeholder: "cross street 2" %>
  <br>
  <%= f.text_field :address, placeholder: "address" %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<%= @result%>

</div>
<br />

app/views/adventures/index.html.erb
ADVENTURES LAND!
<br />
this should show all of the adventures by specific location
<br />

app/views/adventures/new.html.erb
<div class='col-xs-12 text-center'>

<h2>New Adventure!</h2>

<%= render :partial => 'form' %>

<!-- connect with YELP API here: yelp_id, location-city, state, neighborhood, -->

<%= @result%>

</div>
<br />

app/views/adventures/show.html.erb
SHOW ME this ADVENTURE!



<%= @adventure.name  %><br />
<%= @adventure.description  %><br />

<div id="map" data-cloudmadekey="<%= ENV["CLOUDMADE_API_KEY"] %>"></div>


<%= @adventure  %>

<br />
<%= button_to "Delete this Adventure", { action: "destroy", id: @adventure.id }, method: :delete, data: { confirm: "Are you sure?" } %>