config/routes.rb
WheresMyBoba::Application.routes.draw do

  root 'site#index'
  devise_for :users
  resources :site, :users

  get '/users/:id/adventures', to: 'users#adventures', as: :user_adventures
  post '/users/:id/faves', to: 'faves#create', as: :new_fave
  delete '/users/:id/faves', to: 'faves#destroy'

  
  get '/my_boba/search', to: 'my_boba#search', as: :search
  post '/my_boba/results', to: 'my_boba#results', as: :results
  get '/my_boba/adventures', to: 'adventures#all', as: :all_adventures

  get '/my_boba/:yelp_id', to: 'my_boba#show', as: :my_boba

  get 'my_boba/:yelp_id/adventures', to: 'adventures#index', as: :loc_adventures
  get 'my_boba/:yelp_id/adventures/new', to: 'adventures#new', as: :new_adventure
  get 'my_boba/:yelp_id/adventures/:id', to: 'adventures#show', as: :show_adventure
  get 'my_boba/:yelp_id/adventures/:id/edit', to: 'adventures#edit', as: :edit_adventure
  
  post 'my_boba/:yelp_id/adventures', to: 'adventures#create'
  patch 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  put 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  delete 'my_boba/:yelp_id/adventures/:id', to: 'adventures#destroy'

end

app/controllers/my_boba_controller.rb
class MyBobaController < ApplicationController

  def search
  
    render :search
  end

  def results
    location = params[:location]
    @user_loc = (location[0]).to_s.upcase
    results = Bobalocation.get_results(@user_loc)
    @boba_locations = results['businesses']   
    @neighborhood_array = (results['businesses']).sort_by { |biz| biz["location"]['neighborhood']}
    @rated_array = (results['businesses']).sort_by { |biz| biz['rating']}
    geocoder = Graticule.service(:google).new ENV['GOOGLE_API_KEY']
    loc = geocoder.locate("#{location}")
    lat = loc.latitude
    long = loc.longitude
    render :results
  end

  def show
    @id = params[:yelp_id]
    @user = current_user
    @result = Bobalocation.show_location(@id)
    @rating = @result['rating_img_url']
    yelp_id = @result['id']
    hood = @result['location']['neighborhoods']
    unless hood.nil?
      @neighborhood = hood.join(" ")
    end
    addy = @result['location']['address']
    addy.insert(1, @result['location']['city'])
    addy.insert(2, @result['location']['state_code'])
    location = addy.flatten 
    geocoder = Graticule.service(:google).new ENV['GOOGLE_API_KEY']
    loc = geocoder.locate("#{location}")
    lat = loc.latitude
    long = loc.longitude
    @boba = Bobalocation.create(yelp_id: yelp_id, latitude: lat, longitude: long)
    gon.locations = @boba

    a = @result['location']['address']
    b = a.join.to_s
    # coords[0] = [@boba.latitude, @boba.longitude]
    yelp = load_yelp

    @adventures = yelp.search_by_category_filter_and_location('active', b)
    cats = @adventures['businesses'].map { |cat| cat['categories']}


  end




private

  def load_yelp
    consumer_key = 'pXI7O2w2TzCcH7ub3Di5Bw'
    consumer_secret = '-PlNCMY1YN1c0-Lh9H4xNWBSMh0'
    token = '7S78wEVuSybUcAc1legyfpGdPYyhsuAz'
    token_secret = 'A_vgIl-yVGp87fuPZvuyWeSXcEQ'
    keys = {consumer_key: consumer_key, consumer_secret: consumer_secret, token: token, token_secret: token_secret}
    yelp = YelpApi.new(keys)    
  end


end

app/helpers/my_boba_helper.rb
module MyBobaHelper
end

app/views/my_boba/_sidebar.html.erb
<div class='circle'>
    <h3 class='londrina'><%= link_to "Boba Passport", signup_path %></h3>
  </div>

app/views/my_boba/index.html.erb
index page

app/views/my_boba/results.html.erb
<div class='col-xs-4 col-xs-offset-1 left-block'>
  <img src="/assets/boba_penguin.png" class="img-responsive" alt="Responsive image" style='height:200px'>
</div>

<div class='col-xs-7 right-block'>
<h2 class='londrina text-center'> boba near:&nbsp;&nbsp;<%= @user_loc %>&nbsp; </h2>

<h4 class='text-center'> THERE ARE <%= @boba_locations.length %> locations.<br /> click to see adventure details around a location. &nbsp;</h4>


</div>

<div class='col-xs-10 col-xs-offset-1'>
<br />
<table class='table'>
  <thead>
    <tr>
      <th>
        BOBA SPOTTED!
      </th> 
      <th>
        Neighborhood
      </th>
      <th>
        Closed?
      </th>  
      <th>
        Adventures!
      </th> 
    </tr>
  </thead>
  <% @boba_locations.each do |boba_locations| %>
  <tr>
  	<td>
      <a href="/my_boba/<%= boba_locations['id']%>"</a>
      <%= boba_locations['name'] %>
      </a>
  	</td>
  	<td>
      <% if boba_locations['location']['neighborhoods'] != nil %>
      <%= boba_locations['location']['neighborhoods'].join(", ") %>
      <% end %>
      
  	</td>
  	<td>
      <%= boba_locations['is_closed'] %>
  	</td>
    <td>


    </td>
  </tr>
<% end %>
</table>
</div>
<br />
<br />
<br />

app/views/my_boba/search.html.erb
<div class='row col-xs-12 text-center'>


  <div class='row'>
  	<div class='col-xs-10 col-xs-offset-1 text-center'>
  <h3>bot, find me boba.</h3>
  <h4>Search a City and State</h4>
    </div>
  </div>

  <div class='row'>
  	<div class='col-xs-10 col-xs-offset-1'>
    <%= form_tag({:controller=>"my_boba", :action=>"results"}, method: :post) do  %>
    <%= search_field :location, nil, placeholder: "City, State"%>
    <%= submit_tag 'Search!', class: 'btn btn-customGR'%>
    <% end %>
    </div>
  </div>

</div>

app/views/my_boba/show.html.erb
<div class='col-xs-12'>

<div class='row col-xs-12'>
<br />
<% unless @result['is_closed'] = 'true'%>
  <%= image_tag('images/open.png', width: '100px') %>
<% end %>
<br />
</div>

<div class='row text-center'>

<div class='col-xs-5 col-s-4'>

<table class='table'> 
  <thead>
  <%= form_for @user, controller: :faves, action: "create", url: new_fave_path(current_user, :yelp_id => @id ), method: :create do |f| %>

<%= f.button 'I love this boba place!', class: 'btn btn-default' %>
<% end %><br /><br />
  </thead> 
  <tr>
    <td>
      <h1 class="megrim"> <%= @result['name'] %> </h1>
    </td>
  </tr>
  <tr>
    <td>
      <img src='<%= @rating%>' class=''></img>
    </td>
  </tr>
  <tr>
  	<td>
      <strong><%= @neighborhood %></strong>
    </td>
  </tr>
  <tr>
    <td>
      <%= @result['location']['address'].join(" ") %><br />
      <%= @result['location']['city']%>, <%= @result['location']['postal_code']%><br />
      <%= @result['display_phone']%>
    </td>
  </tr>
  <tr>
  	<td>
      <% unless (@result['location']['cross_streets']).nil? %>
      By
      <%= @result['location']['cross_streets']%>
      <% end %>
      <br />
    </td>
  </tr>
  <tr>
    <td>

      <br />
    </td>
  </tr>
</table>
</div>

<div class='col-xs-7 col-s-7'>
<!--add map here -->
<div id="map-canvas" style='height:230px'/>

</div>
<br />
</div>

<div class='row col-xs-12 center-block'>
<%= link_to 'create an adventure nearby', {controller: :adventures,action: 'new', url: new_adventure_path(current_user)}, method: :get %>
</div>

<%= @boba.latitude %>
<%= @boba.longitude %>

<div class='row col-xs-12 center-block'>

</div>
<br />
<div class='col-xs-12'>
<table class='table'>
<% @adventures['businesses'].each do |adventures| %>
  <tr>
    <td>
      <%= adventures['name'] %>
      </a>
    </td>
    <td>
      <% if adventures['categories'] != nil %>
      <%= adventures['categories'].join(", ") %>
      <% end %>
      
    </td>

    <td>


    </td>
  </tr>
<% end %>
</table>

</div>