config/routes.rb
WheresMyBoba::Application.routes.draw do

  root 'site#index'
  devise_for :users
  resources :site, :users

  get '/users/:id/adventures', to: 'users#adventures', as: :user_adventures
  post '/users/:id/faves', to: 'faves#create', as: :new_fave
  delete '/users/:id/faves', to: 'faves#destroy'

  
  get '/my_boba/search', to: 'my_boba#search', as: :search
  post '/my_boba/results', to: 'my_boba#results', as: :results
  get '/my_boba/adventures', to: 'adventures#all', as: :all_adventures

  get '/my_boba/:yelp_id', to: 'my_boba#show', as: :my_boba

  get 'my_boba/:yelp_id/adventures', to: 'adventures#index', as: :loc_adventures
  get 'my_boba/:yelp_id/adventures/new', to: 'adventures#new', as: :new_adventure
  get 'my_boba/:yelp_id/adventures/:id', to: 'adventures#show', as: :show_adventure
  get 'my_boba/:yelp_id/adventures/:id/edit', to: 'adventures#edit', as: :edit_adventure
  
  post 'my_boba/:yelp_id/adventures', to: 'adventures#create'
  patch 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  put 'my_boba/:yelp_id/adventures/:id', to: 'adventures#update'
  delete 'my_boba/:yelp_id/adventures/:id', to: 'adventures#destroy'

end

app/views/layouts/_header.html.erb
<header>

<%= render partial: "/layouts/nav" %>


<%= render partial: "/layouts/title" %>

</header>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top col-xs-12">
  <div class="navbar-inner left-block">
      <nav>
        <ul class="nav nav-pills">
            <% if signed_in? %>

              <li><%= link_to "my passport.", current_user %></li>

              <li><%= link_to "my adventures", user_adventures_path(current_user.id) %></li>
              <li><%= link_to "sign out", destroy_user_session_path, method: "delete"%></li>
              <li><%= link_to "search for boba.", search_path %></li>
            <% else %>
              <li><%= link_to "adventures!", all_adventures_path %></li>
              <li><%= link_to "search for boba.", search_path %></li>
              <li><%= link_to "sign in.", new_user_session_path %></li>
              <li><%= link_to "sign up - get a passport.", new_user_registration_path %></li>
            <% end %>

        </ul>
      </nav>
  </div>
</div>

app/views/layouts/_title.html.erb
<div class='row'>
<div class='col-xs-12 text-center'>

<h1 class='banner londrina'> boba adventures </h1>





</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boba Adventures!</title>
  <link href='http://fonts.googleapis.com/css?family=Muli|Londrina+Shadow|Megrim' rel='stylesheet' type='text/css'>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%ENV['GOOGLE_API_KEY']%>&sensor=false"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body class="container-fluid col-xs-12">
  <%= render partial: 'layouts/header' %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>

</body>
</html>